In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('manufacturing_data.csv')

In [5]:
df.head()

,recordDate,fiscalQuarter,productionDept,dayOfWeek,team,plannedEfficiency,standardMinuteValue,workInProgress,overtimeMinutes,performanceBonus,idleMinutes,idleWorkers,styleChangeCount,workerCount,efficiencyScore
0,2/24/2015,Q4,Stitching Unit,Tuesday,Line-S1,0.6,22.53,708.0,5040,0,0.0,0,Minor Style Revision,42.0,0.268214
1,1/19/2015,Q3,Stitching Unit,Monday,Line-F3,0.8,11.41,1028.0,4380,50,0.0,0,No Style Change,31.0,0.800359
2,1/6/2015,Q1,Finishing & Quality,Tuesday,Line-C2,0.8,2.90,NaN,1440,0,0.0,0,No Style Change,8.0,0.681061
3,2/24/2015,Q4,Finishing & Quality,Tuesday,Line-S2,0.7,3.90,NaN,960,0,0.0,0,No Style Change,8.0,0.325000
4,1/4/2015,Q1,Finishing & Quality,Sunday,Line-C1,0.8,2.90,NaN,960,0,0.0,0,No Style Change,8.0,0.667604

In [6]:
# Removing space in the values of the column
df['productionDept'] = df['productionDept'].str.strip()

Dropping all the rows which has the production dept as stiching unit.

In [7]:
# Dropping the rows of production dept which is having stiching unit
df = df[df['productionDept']!='Stitching Unit']

In [8]:
# Value Count For ProductionDept
df['productionDept'].value_counts()

productionDept
Finishing & Quality    506
Name: count, dtype: int64

In [9]:
df.describe()

,plannedEfficiency,standardMinuteValue,workInProgress,overtimeMinutes,performanceBonus,idleMinutes,idleWorkers,workerCount,efficiencyScore
count,506.000000,506.000000,0.0,506.000000,506.000000,506.0,506.0,506.000000,506.000000
mean,0.737352,3.887036,NaN,1917.154150,29.644269,0.0,0.0,10.252964,0.752951
std,0.091512,0.594110,NaN,1776.698408,244.130042,0.0,0.0,4.007819,0.197021
min,0.350000,2.900000,NaN,0.000000,0.000000,0.0,0.0,2.000000,0.235795
25%,0.700000,3.900000,NaN,960.000000,0.000000,0.0,0.0,8.000000,0.631606
50%,0.750000,3.940000,NaN,1440.000000,0.000000,0.0,0.0,8.000000,0.805909
75%,0.800000,4.150000,NaN,1920.000000,0.000000,0.0,0.0,11.750000,0.906364
max,0.800000,5.130000,NaN,15000.000000,3600.000000,0.0,0.0,28.000000,1.120437

In [10]:
# Encoding Categorical feature

# Encoding for fiscalQuarter, dayOfWeek and styleChangeCount

from sklearn.preprocessing import LabelEncoder

L = LabelEncoder()

# Columns to encode
columns_to_encode_ord = ['productionDept', 'team']

for col in columns_to_encode_ord:
    df[col] = L.fit_transform(df[col])

In [11]:
# One-Hot Encoding for fiscalQuarter, dayOfWeek and styleCountChange
columns_to_encode_ohe = ['fiscalQuarter', 'dayOfWeek', 'styleChangeCount']

df = pd.get_dummies(df, columns = columns_to_encode_ohe, drop_first=True, dtype=int)
df.head()

,recordDate,productionDept,team,plannedEfficiency,standardMinuteValue,workInProgress,overtimeMinutes,performanceBonus,idleMinutes,idleWorkers,...,efficiencyScore,fiscalQuarter_Q2,fiscalQuarter_Q3,fiscalQuarter_Q4,fiscalQuarter_Q5,dayOfWeek_Saturday,dayOfWeek_Sunday,dayOfWeek_Thursday,dayOfWeek_Tuesday,dayOfWeek_Wednesday
2,1/6/2015,0,1,0.8,2.90,NaN,1440,0,0.0,0,...,0.681061,0,0,0,0,0,0,0,1,0
3,2/24/2015,0,10,0.7,3.90,NaN,960,0,0.0,0,...,0.325000,0,0,1,0,0,0,0,1,0
4,1/4/2015,0,0,0.8,2.90,NaN,960,0,0.0,0,...,0.667604,0,0,0,0,0,1,0,0,0
6,2/26/2015,0,9,0.5,3.94,NaN,3360,0,0.0,0,...,0.768847,0,0,1,0,0,0,1,0,0
7,2/28/2015,0,9,0.5,3.94,NaN,3360,0,0.0,0,...,0.768847,0,0,1,0,1,0,0,0,0

In [12]:
df['recordDate'] = pd.to_datetime(df['recordDate'])
df['month'] = df['recordDate'].dt.month
df['day'] = df['recordDate'].dt.day
df.head(10)

,recordDate,productionDept,team,plannedEfficiency,standardMinuteValue,workInProgress,overtimeMinutes,performanceBonus,idleMinutes,idleWorkers,...,fiscalQuarter_Q3,fiscalQuarter_Q4,fiscalQuarter_Q5,dayOfWeek_Saturday,dayOfWeek_Sunday,dayOfWeek_Thursday,dayOfWeek_Tuesday,dayOfWeek_Wednesday,month,day
2,2015-01-06,0,1,0.80,2.90,NaN,1440,0,0.0,0,...,0,0,0,0,0,0,1,0,1,6
3,2015-02-24,0,10,0.70,3.90,NaN,960,0,0.0,0,...,0,1,0,0,0,0,1,0,2,24
4,2015-01-04,0,0,0.80,2.90,NaN,960,0,0.0,0,...,0,0,0,0,1,0,0,0,1,4
6,2015-02-26,0,9,0.50,3.94,NaN,3360,0,0.0,0,...,0,1,0,0,0,1,0,0,2,26
7,2015-02-28,0,9,0.50,3.94,NaN,3360,0,0.0,0,...,0,1,0,1,0,0,0,0,2,28
11,2015-01-04,0,2,0.80,3.94,NaN,6600,0,0.0,0,...,0,0,0,0,1,0,0,0,1,4
13,2015-02-19,0,11,0.50,5.13,NaN,2880,0,0.0,0,...,1,0,0,0,0,1,0,0,2,19
15,2015-01-11,0,11,0.75,4.15,NaN,1440,0,0.0,0,...,0,0,0,0,1,0,0,0,1,11
22,2015-02-08,0,9,0.80,3.94,NaN,1200,0,0.0,0,...,0,0,0,0,1,0,0,0,2,8
23,2015-02-22,0,9,0.80,3.94,NaN,2880,0,0.0,0,...,0,1,0,0,1,0,0,0,2,22

In [13]:
df.columns.tolist()

['recordDate',
 'productionDept',
 'team',
 'plannedEfficiency',
 'standardMinuteValue',
 'workInProgress',
 'overtimeMinutes',
 'performanceBonus',
 'idleMinutes',
 'idleWorkers',
 'workerCount',
 'efficiencyScore',
 'fiscalQuarter_Q2',
 'fiscalQuarter_Q3',
 'fiscalQuarter_Q4',
 'fiscalQuarter_Q5',
 'dayOfWeek_Saturday',
 'dayOfWeek_Sunday',
 'dayOfWeek_Thursday',
 'dayOfWeek_Tuesday',
 'dayOfWeek_Wednesday',
 'month',
 'day']

In [14]:
df = df.drop('workInProgress', axis=1)

In [15]:
df.columns.tolist()

['recordDate',
 'productionDept',
 'team',
 'plannedEfficiency',
 'standardMinuteValue',
 'overtimeMinutes',
 'performanceBonus',
 'idleMinutes',
 'idleWorkers',
 'workerCount',
 'efficiencyScore',
 'fiscalQuarter_Q2',
 'fiscalQuarter_Q3',
 'fiscalQuarter_Q4',
 'fiscalQuarter_Q5',
 'dayOfWeek_Saturday',
 'dayOfWeek_Sunday',
 'dayOfWeek_Thursday',
 'dayOfWeek_Tuesday',
 'dayOfWeek_Wednesday',
 'month',
 'day']

In [16]:
df['overtimePerWorker'] = df['overtimeMinutes'] / df['workerCount']
df['overtimePerWorker']

2       180.0
3       120.0
4       120.0
6       420.0
7       420.0
        ...
1190    120.0
1192    420.0
1193    120.0
1194      0.0
1196    120.0
Name: overtimePerWorker, Length: 506, dtype: float64

In [17]:
# df['efficiencyGap'] = df['plannedEfficiency'] - df['efficiencyScore']
# df['efficiencyGap'] = df['efficiencyGap'].abs()
# df['efficiencyGap']

In [18]:
df['actualEfficiency'] = df['efficiencyScore']/df['plannedEfficiency']
df['actualEfficiency']

2       0.851326
3       0.464286
4       0.834505
6       1.537694
7       1.537694
          ...
1190    1.607083
1192    0.506349
1193    1.595000
1194    1.440571
1196    0.630060
Name: actualEfficiency, Length: 506, dtype: float64

In [19]:
df['bonusPerMinute'] = df['performanceBonus']/df['standardMinuteValue']
df['bonusPerMinute']

2         0.000000
3         0.000000
4         0.000000
6         0.000000
7         0.000000
           ...
1190      0.000000
1192      0.000000
1193      0.000000
1194    730.964467
1196      0.000000
Name: bonusPerMinute, Length: 506, dtype: float64

In [20]:
df.isnull().sum().sort_values(ascending=False)

recordDate             0
productionDept         0
team                   0
plannedEfficiency      0
standardMinuteValue    0
overtimeMinutes        0
performanceBonus       0
idleMinutes            0
idleWorkers            0
workerCount            0
efficiencyScore        0
fiscalQuarter_Q2       0
fiscalQuarter_Q3       0
fiscalQuarter_Q4       0
fiscalQuarter_Q5       0
dayOfWeek_Saturday     0
dayOfWeek_Sunday       0
dayOfWeek_Thursday     0
dayOfWeek_Tuesday      0
dayOfWeek_Wednesday    0
month                  0
day                    0
overtimePerWorker      0
actualEfficiency       0
bonusPerMinute         0
dtype: int64

In [21]:
# Normalizaton of features
from sklearn.preprocessing import MinMaxScaler

features = [
    'standardMinuteValue',
    'overtimeMinutes',
    'performanceBonus',
    'idleWorkers',
    'workerCount',
    'month',
    'day',
    'bonusPerMinute'
]
S = MinMaxScaler()

df[features] = S.fit_transform(df[features])
df.head(10)

,recordDate,productionDept,team,plannedEfficiency,standardMinuteValue,overtimeMinutes,performanceBonus,idleMinutes,idleWorkers,workerCount,...,dayOfWeek_Saturday,dayOfWeek_Sunday,dayOfWeek_Thursday,dayOfWeek_Tuesday,dayOfWeek_Wednesday,month,day,overtimePerWorker,actualEfficiency,bonusPerMinute
2,2015-01-06,0,1,0.80,0.000000,0.096,0.0,0.0,0.0,0.230769,...,0,0,0,1,0,0.0,0.166667,180.0,0.851326,0.0
3,2015-02-24,0,10,0.70,0.448430,0.064,0.0,0.0,0.0,0.230769,...,0,0,0,1,0,0.5,0.766667,120.0,0.464286,0.0
4,2015-01-04,0,0,0.80,0.000000,0.064,0.0,0.0,0.0,0.230769,...,0,1,0,0,0,0.0,0.100000,120.0,0.834505,0.0
6,2015-02-26,0,9,0.50,0.466368,0.224,0.0,0.0,0.0,0.230769,...,0,0,1,0,0,0.5,0.833333,420.0,1.537694,0.0
7,2015-02-28,0,9,0.50,0.466368,0.224,0.0,0.0,0.0,0.230769,...,1,0,0,0,0,0.5,0.900000,420.0,1.537694,0.0
11,2015-01-04,0,2,0.80,0.466368,0.440,0.0,0.0,0.0,0.692308,...,0,1,0,0,0,0.0,0.100000,330.0,1.077099,0.0
13,2015-02-19,0,11,0.50,1.000000,0.192,0.0,0.0,0.0,0.384615,...,0,0,1,0,0,0.5,0.600000,240.0,1.632812,0.0
15,2015-01-11,0,11,0.75,0.560538,0.096,0.0,0.0,0.0,0.230769,...,0,1,0,0,0,0.0,0.333333,180.0,1.247096,0.0
22,2015-02-08,0,9,0.80,0.466368,0.080,0.0,0.0,0.0,0.307692,...,0,1,0,0,0,0.5,0.233333,120.0,1.116333,0.0
23,2015-02-22,0,9,0.80,0.466368,0.192,0.0,0.0,0.0,0.384615,...,0,1,0,0,0,0.5,0.700000,240.0,0.909187,0.0

In [22]:
X = df.drop(columns=['efficiencyScore', 'recordDate', 'idleMinutes', 'idleWorkers'])
y = df['efficiencyScore']

In [23]:
X

,productionDept,team,plannedEfficiency,standardMinuteValue,overtimeMinutes,performanceBonus,workerCount,fiscalQuarter_Q2,fiscalQuarter_Q3,fiscalQuarter_Q4,...,dayOfWeek_Saturday,dayOfWeek_Sunday,dayOfWeek_Thursday,dayOfWeek_Tuesday,dayOfWeek_Wednesday,month,day,overtimePerWorker,actualEfficiency,bonusPerMinute
2,0,1,0.8,0.000000,0.096,0.0,0.230769,0,0,0,...,0,0,0,1,0,0.0,0.166667,180.0,0.851326,0.000000
3,0,10,0.7,0.448430,0.064,0.0,0.230769,0,0,1,...,0,0,0,1,0,0.5,0.766667,120.0,0.464286,0.000000
4,0,0,0.8,0.000000,0.064,0.0,0.230769,0,0,0,...,0,1,0,0,0,0.0,0.100000,120.0,0.834505,0.000000
6,0,9,0.5,0.466368,0.224,0.0,0.230769,0,0,1,...,0,0,1,0,0,0.5,0.833333,420.0,1.537694,0.000000
7,0,9,0.5,0.466368,0.224,0.0,0.230769,0,0,1,...,1,0,0,0,0,0.5,0.900000,420.0,1.537694,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1190,0,0,0.5,0.560538,0.064,0.0,0.230769,0,0,1,...,0,0,0,1,0,0.0,0.866667,120.0,1.607083,0.000000
1192,0,3,0.7,0.762332,0.224,0.0,0.230769,0,0,0,...,0,0,0,1,0,1.0,0.066667,420.0,0.506349,0.000000
1193,0,4,0.5,0.000000,0.064,0.0,0.230769,0,0,0,...,1,0,0,0,0,1.0,0.200000,120.0,1.595000,0.000000
1194,0,3,0.6,0.466368,0.000,0.8,0.384615,1,0,0,...,0,0,0,0,0,1.0,0.266667,0.0,1.440571,0.588832
1196,0,8,0.7,0.000000,0.064,0.0,0.230769,1,0,0,...,0,1,0,0,0,1.0,0.233333,120.0,0.630060,0.000000

In [24]:
y

2       0.681061
3       0.325000
4       0.667604
6       0.768847
7       0.768847
          ...
1190    0.803542
1192    0.354444
1193    0.797500
1194    0.864343
1196    0.441042
Name: efficiencyScore, Length: 506, dtype: float64

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((404, 21), (102, 21), (404,), (102,))

# Simple Linear Regression

In [26]:
from sklearn.linear_model import LinearRegression

L = LinearRegression()
L.fit(X_train, y_train)
y_pred_linear = L.predict(X_test)

In [27]:
from sklearn.metrics import mean_squared_error, r2_score

mse_linear = mean_squared_error(y_test, y_pred_linear)
r2_linear = r2_score(y_test, y_pred_linear)

print(f"Mean Squared Error (Simple Linear Regression): {mse_linear}")
print(f"R-squared (Simple Linear Regression): {r2_linear}")

Mean Squared Error (Simple Linear Regression): 0.005645691123361546
R-squared (Simple Linear Regression): 0.8422333775615899

# Decision Tree Regressor

In [28]:
from sklearn.tree import DecisionTreeRegressor

DT = DecisionTreeRegressor()
DT.fit(X_train, y_train)
y_pred_decision = DT.predict(X_test)

In [29]:
from sklearn.metrics import mean_squared_error, r2_score

mse_decision = mean_squared_error(y_test, y_pred_decision)
r2_decision = r2_score(y_test, y_pred_decision)

print(f"Mean Squared Error (Decision Tree Regressor): {mse_decision:.5f}")
print(f"R-squared (Decision Tree Regressor): {r2_decision:.5f}")

Mean Squared Error (Decision Tree Regressor): 0.00194
R-squared (Decision Tree Regressor): 0.94570

# Random Forest Regressor

In [30]:
from sklearn.ensemble import RandomForestRegressor

RF = RandomForestRegressor()
RF.fit(X_train, y_train)
y_pred_random = RF.predict(X_test)

In [31]:
from sklearn.metrics import mean_squared_error, r2_score

mse_random = mean_squared_error(y_test, y_pred_random)
r2_random = r2_score(y_test, y_pred_random)

print(f"Mean Squared Error (Random Forest Regressor): {mse_random:.5f}")
print(f"R-squared (Random Forest Regressor): {r2_random:.5f}")

Mean Squared Error (Random Forest Regressor): 0.00166
R-squared (Random Forest Regressor): 0.95357

# Gradient Boosting Regressor

In [32]:
from sklearn.ensemble import GradientBoostingRegressor

GB = GradientBoostingRegressor()
GB.fit(X_train, y_train)
y_pred_gradient_boosting = GB.predict(X_test)

In [33]:
from sklearn.metrics import mean_squared_error, r2_score

mse_gradient_boosting = mean_squared_error(y_test, y_pred_gradient_boosting)
r2_gradient_boosting = r2_score(y_test, y_pred_gradient_boosting)

print(f"Mean Squared Error (Gradient Boosting Regressor): {mse_gradient_boosting:.5f}")
print(f"R-squared (Gradient Boosting Regressor): {r2_gradient_boosting:.5f}")

Mean Squared Error (Gradient Boosting Regressor): 0.00069
R-squared (Gradient Boosting Regressor): 0.98086