In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('manufacturing_data.csv')

In [6]:
df.head()

,recordDate,fiscalQuarter,productionDept,dayOfWeek,team,plannedEfficiency,standardMinuteValue,workInProgress,overtimeMinutes,performanceBonus,idleMinutes,idleWorkers,styleChangeCount,workerCount,efficiencyScore
0,2/24/2015,Q4,Stitching Unit,Tuesday,Line-S1,0.6,22.53,708.0,5040,0,0.0,0,Minor Style Revision,42.0,0.268214
1,1/19/2015,Q3,Stitching Unit,Monday,Line-F3,0.8,11.41,1028.0,4380,50,0.0,0,No Style Change,31.0,0.800359
2,1/6/2015,Q1,Finishing & Quality,Tuesday,Line-C2,0.8,2.90,NaN,1440,0,0.0,0,No Style Change,8.0,0.681061
3,2/24/2015,Q4,Finishing & Quality,Tuesday,Line-S2,0.7,3.90,NaN,960,0,0.0,0,No Style Change,8.0,0.325000
4,1/4/2015,Q1,Finishing & Quality,Sunday,Line-C1,0.8,2.90,NaN,960,0,0.0,0,No Style Change,8.0,0.667604

In [7]:
df = df.dropna(subset=['workInProgress'])

In [8]:
df['productionDept'].value_counts()

productionDept
Stitching Unit    691
Name: count, dtype: int64

In [9]:
df.describe()

,plannedEfficiency,standardMinuteValue,workInProgress,overtimeMinutes,performanceBonus,idleMinutes,idleWorkers,workerCount,efficiencyScore
count,691.000000,691.000000,691.000000,691.000000,691.000000,691.000000,691.000000,691.000000,691.000000
mean,0.723980,23.245412,1190.465991,6508.205499,44.483357,1.264834,0.639653,52.445731,0.722013
std,0.102006,6.976497,1837.455001,2864.505604,27.596591,16.712923,4.283652,9.417353,0.154784
min,0.070000,10.050000,7.000000,0.000000,0.000000,0.000000,0.000000,26.000000,0.233705
25%,0.700000,18.790000,774.500000,4560.000000,30.000000,0.000000,0.000000,52.000000,0.661470
50%,0.750000,22.520000,1039.000000,6840.000000,45.000000,0.000000,0.000000,57.000000,0.750608
75%,0.800000,28.080000,1252.500000,7200.000000,60.000000,0.000000,0.000000,58.000000,0.800402
max,0.800000,54.560000,23122.000000,25920.000000,138.000000,300.000000,45.000000,89.000000,1.100484

In [10]:
# To Remove Space In The Columns
df['productionDept'] = df['productionDept'].str.strip()

In [11]:
# Encoding categorical Feature

# Encoding for fiscalQuarter, dayOfWeek and styleChangeCount.

from sklearn.preprocessing import LabelEncoder

L = LabelEncoder()

columns_to_encode_ord = ['fiscalQuarter', 'dayOfWeek', 'styleChangeCount']

for col in columns_to_encode_ord:
    df[col] = L.fit_transform(df[col])

In [12]:
# One-Hot Encoding for poductionDept and team
columns_to_encode_ohe = ['productionDept', 'team']

df = pd.get_dummies(df, columns = columns_to_encode_ohe, drop_first=True, dtype=int)
df.head()

,recordDate,fiscalQuarter,dayOfWeek,plannedEfficiency,standardMinuteValue,workInProgress,overtimeMinutes,performanceBonus,idleMinutes,idleWorkers,...,team_Line-F1,team_Line-F2,team_Line-F3,team_Line-P1,team_Line-P2,team_Line-Q1,team_Line-Q2,team_Line-S1,team_Line-S2,team_Line-S3
0,2/24/2015,3,4,0.60,22.53,708.0,5040,0,0.0,0,...,0,0,0,0,0,0,0,1,0,0
1,1/19/2015,2,0,0.80,11.41,1028.0,4380,50,0.0,0,...,0,0,1,0,0,0,0,0,0,0
5,2/16/2015,2,0,0.80,30.10,461.0,0,0,0.0,0,...,0,1,0,0,0,0,0,0,0,0
8,1/24/2015,3,1,0.65,22.52,1295.0,10170,26,0.0,0,...,0,0,0,0,0,0,0,0,0,0
9,3/5/2015,0,3,0.75,18.79,1228.0,6240,45,0.0,0,...,0,0,0,0,0,1,0,0,0,0

In [13]:
df['recordDate'] = pd.to_datetime(df['recordDate'])
df['month'] = df['recordDate'].dt.month
df['day'] = df['recordDate'].dt.day
df.head(10)

,recordDate,fiscalQuarter,dayOfWeek,plannedEfficiency,standardMinuteValue,workInProgress,overtimeMinutes,performanceBonus,idleMinutes,idleWorkers,...,team_Line-F3,team_Line-P1,team_Line-P2,team_Line-Q1,team_Line-Q2,team_Line-S1,team_Line-S2,team_Line-S3,month,day
0,2015-02-24,3,4,0.60,22.53,708.0,5040,0,0.0,0,...,0,0,0,0,0,1,0,0,2,24
1,2015-01-19,2,0,0.80,11.41,1028.0,4380,50,0.0,0,...,1,0,0,0,0,0,0,0,1,19
5,2015-02-16,2,0,0.80,30.10,461.0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,2,16
8,2015-01-24,3,1,0.65,22.52,1295.0,10170,26,0.0,0,...,0,0,0,0,0,0,0,0,1,24
9,2015-03-05,0,3,0.75,18.79,1228.0,6240,45,0.0,0,...,0,0,0,1,0,0,0,0,3,5
10,2015-02-02,0,0,0.70,20.55,9792.0,6480,60,0.0,0,...,0,1,0,0,0,0,0,0,2,2
12,2015-01-04,0,2,0.80,26.16,1033.0,7080,63,0.0,0,...,0,0,0,0,0,1,0,0,1,4
14,2015-01-14,1,5,0.80,25.90,1150.0,10170,70,0.0,0,...,0,0,0,0,0,0,0,0,1,14
16,2015-02-12,1,3,0.80,22.52,1327.0,0,113,0.0,0,...,0,0,0,0,0,0,1,0,2,12
17,2015-02-14,1,1,0.60,11.41,1039.0,2280,23,0.0,0,...,0,1,0,0,0,0,0,0,2,14

In [14]:
df.columns.tolist()

['recordDate',
 'fiscalQuarter',
 'dayOfWeek',
 'plannedEfficiency',
 'standardMinuteValue',
 'workInProgress',
 'overtimeMinutes',
 'performanceBonus',
 'idleMinutes',
 'idleWorkers',
 'styleChangeCount',
 'workerCount',
 'efficiencyScore',
 'team_Line-C2',
 'team_Line-F1',
 'team_Line-F2',
 'team_Line-F3',
 'team_Line-P1',
 'team_Line-P2',
 'team_Line-Q1',
 'team_Line-Q2',
 'team_Line-S1',
 'team_Line-S2',
 'team_Line-S3',
 'month',
 'day']

In [15]:
# Missing Value Imputation
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

df['workInProgress'] = imputer.fit_transform(df[['workInProgress']])

In [16]:
# Feature Engineering
# Adding new feature - efficiencyPerWorker
df['efficiencyPerWorker'] = df['workInProgress'] / (df['workerCount'])
df['efficiencyPerWorker']

0       16.857143
1       33.161290
5        7.813559
8       22.920354
9       23.615385
          ...
1183    19.894737
1185    20.152542
1187    15.517857
1191     7.120690
1195     7.525424
Name: efficiencyPerWorker, Length: 691, dtype: float64

In [17]:
# Adding new feature - overtime_ratio
df['overtime_ratio'] = df['overtimeMinutes'] / (df['workInProgress'])
df['overtime_ratio']

0        7.118644
1        4.260700
5        0.000000
8        7.853282
9        5.081433
          ...
1183     7.460317
1185     8.931876
1187     7.733026
1191    23.535109
1195     0.000000
Name: overtime_ratio, Length: 691, dtype: float64

In [18]:
# Adding new feature - efficiencyGap
df['efficiencyGap'] = df['plannedEfficiency'] - df['efficiencyScore']
df['efficiencyGap'] = df['efficiencyGap'].abs()
df['efficiencyGap']

0       0.331786
1       0.000359
5       0.000980
8       0.000417
9       0.000396
          ...
1183    0.050038
1185    0.050502
1187    0.000529
1191    0.000481
1195    0.138859
Name: efficiencyGap, Length: 691, dtype: float64

In [19]:
# Adding a new feature - overtimePerWorker
df['overtimePerWorker'] = df['overtimeMinutes'] / df['workerCount']
df['overtimePerWorker']

0       120.000000
1       141.290323
5         0.000000
8       180.000000
9       120.000000
           ...
1183    148.421053
1185    180.000000
1187    120.000000
1191    167.586207
1195      0.000000
Name: overtimePerWorker, Length: 691, dtype: float64

In [20]:
# Adding new feature - workloadPerWorker
df['workloadPerWorker'] = df['standardMinuteValue'] * df['workInProgress'] / df['workerCount']
df['workloadPerWorker']

0       379.791429
1       378.370323
5       235.188136
8       516.166372
9       443.733077
           ...
1183    448.029474
1185    527.190508
1187    472.984286
1191    156.512759
1195    226.515254
Name: workloadPerWorker, Length: 691, dtype: float64

In [21]:
# Adding a new feature - efficiencyPerWorker
df['efficiencyPerWorker'] = df['workInProgress'] / df['workerCount']
df['efficiencyPerWorker']

0       16.857143
1       33.161290
5        7.813559
8       22.920354
9       23.615385
          ...
1183    19.894737
1185    20.152542
1187    15.517857
1191     7.120690
1195     7.525424
Name: efficiencyPerWorker, Length: 691, dtype: float64

In [22]:
df['efficiencyPerWorker'].value_counts()

efficiencyPerWorker
14.315789    2
18.982456    2
24.842105    2
24.508772    2
24.947368    2
            ..
15.122449    1
26.000000    1
27.078261    1
12.452174    1
15.445378    1
Name: count, Length: 671, dtype: int64

In [23]:
df.isnull().sum().sort_values(ascending=False)

recordDate             0
fiscalQuarter          0
dayOfWeek              0
plannedEfficiency      0
standardMinuteValue    0
workInProgress         0
overtimeMinutes        0
performanceBonus       0
idleMinutes            0
idleWorkers            0
styleChangeCount       0
workerCount            0
efficiencyScore        0
team_Line-C2           0
team_Line-F1           0
team_Line-F2           0
team_Line-F3           0
team_Line-P1           0
team_Line-P2           0
team_Line-Q1           0
team_Line-Q2           0
team_Line-S1           0
team_Line-S2           0
team_Line-S3           0
month                  0
day                    0
efficiencyPerWorker    0
overtime_ratio         0
efficiencyGap          0
overtimePerWorker      0
workloadPerWorker      0
dtype: int64

In [24]:
# Normalizaton of features
from sklearn.preprocessing import MinMaxScaler

features = [
    'fiscalQuarter',
    'standardMinuteValue',
    'workInProgress',
    'overtimeMinutes',
    'performanceBonus',
    'idleMinutes',
    'idleWorkers',
    'styleChangeCount',
    'workerCount',
    'month',
    'day'
]
S = MinMaxScaler()

df[features] = S.fit_transform(df[features])
df.head(10)

,recordDate,fiscalQuarter,dayOfWeek,plannedEfficiency,standardMinuteValue,workInProgress,overtimeMinutes,performanceBonus,idleMinutes,idleWorkers,...,team_Line-S1,team_Line-S2,team_Line-S3,month,day,efficiencyPerWorker,overtime_ratio,efficiencyGap,overtimePerWorker,workloadPerWorker
0,2015-02-24,0.75,4,0.60,0.280386,0.030327,0.194444,0.000000,0.0,0.0,...,1,0,0,0.5,0.766667,16.857143,7.118644,0.331786,120.000000,379.791429
1,2015-01-19,0.50,0,0.80,0.030555,0.044170,0.168981,0.362319,0.0,0.0,...,0,0,0,0.0,0.600000,33.161290,4.260700,0.000359,141.290323,378.370323
5,2015-02-16,0.50,0,0.80,0.450461,0.019641,0.000000,0.000000,0.0,0.0,...,0,0,0,0.5,0.500000,7.813559,0.000000,0.000980,0.000000,235.188136
8,2015-01-24,0.75,1,0.65,0.280162,0.055721,0.392361,0.188406,0.0,0.0,...,0,0,0,0.0,0.766667,22.920354,7.853282,0.000417,180.000000,516.166372
9,2015-03-05,0.00,3,0.75,0.196360,0.052823,0.240741,0.326087,0.0,0.0,...,0,0,0,1.0,0.133333,23.615385,5.081433,0.000396,120.000000,443.733077
10,2015-02-02,0.00,0,0.70,0.235902,0.423318,0.250000,0.434783,0.0,0.0,...,0,0,0,0.5,0.033333,181.333333,0.661765,0.000398,120.000000,3726.400000
12,2015-01-04,0.00,2,0.80,0.361941,0.044387,0.273148,0.456522,0.0,0.0,...,1,0,0,0.0,0.100000,17.508475,6.853824,0.000319,120.000000,458.021695
14,2015-01-14,0.25,5,0.80,0.356100,0.049448,0.392361,0.507246,0.0,0.0,...,0,0,0,0.0,0.433333,20.353982,8.843478,0.100145,180.000000,527.168142
16,2015-02-12,0.25,3,0.80,0.280162,0.057106,0.000000,0.818841,0.0,0.0,...,0,1,0,0.5,0.366667,23.078261,0.000000,0.200345,0.000000,519.722435
17,2015-02-14,0.25,1,0.60,0.030555,0.044646,0.087963,0.166667,0.0,0.0,...,0,0,0,0.5,0.433333,18.890909,2.194418,0.000448,41.454545,215.545273

In [25]:
## Storing all features in X and target variable in y
X = df.drop(columns=['efficiencyScore', 'recordDate', 'idleMinutes', 'idleWorkers'])
y = df['efficiencyScore']

In [26]:
X

,fiscalQuarter,dayOfWeek,plannedEfficiency,standardMinuteValue,workInProgress,overtimeMinutes,performanceBonus,styleChangeCount,workerCount,team_Line-C2,...,team_Line-S1,team_Line-S2,team_Line-S3,month,day,efficiencyPerWorker,overtime_ratio,efficiencyGap,overtimePerWorker,workloadPerWorker
0,0.75,4,0.60,0.280386,0.030327,0.194444,0.000000,0.5,0.253968,0,...,1,0,0,0.5,0.766667,16.857143,7.118644,0.331786,120.000000,379.791429
1,0.50,0,0.80,0.030555,0.044170,0.168981,0.362319,1.0,0.079365,0,...,0,0,0,0.0,0.600000,33.161290,4.260700,0.000359,141.290323,378.370323
5,0.50,0,0.80,0.450461,0.019641,0.000000,0.000000,1.0,0.523810,0,...,0,0,0,0.5,0.500000,7.813559,0.000000,0.000980,0.000000,235.188136
8,0.75,1,0.65,0.280162,0.055721,0.392361,0.188406,1.0,0.484127,0,...,0,0,0,0.0,0.766667,22.920354,7.853282,0.000417,180.000000,516.166372
9,0.00,3,0.75,0.196360,0.052823,0.240741,0.326087,1.0,0.412698,0,...,0,0,0,1.0,0.133333,23.615385,5.081433,0.000396,120.000000,443.733077
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1183,0.50,4,0.70,0.280162,0.048756,0.326389,0.362319,1.0,0.492063,0,...,0,0,1,0.0,0.633333,19.894737,7.460317,0.050038,148.421053,448.029474
1185,0.25,3,0.80,0.361941,0.051136,0.409722,0.543478,1.0,0.523810,0,...,1,0,0,0.0,0.233333,20.152542,8.931876,0.050502,180.000000,527.190508
1187,0.25,2,0.60,0.458998,0.037292,0.259259,0.000000,0.5,0.476190,1,...,0,0,0,1.0,0.233333,15.517857,7.733026,0.000529,120.000000,472.984286
1191,0.00,5,0.70,0.268030,0.017564,0.375000,0.289855,1.0,0.507937,0,...,0,0,0,0.0,0.200000,7.120690,23.535109,0.000481,167.586207,156.512759
1195,0.50,3,0.75,0.450461,0.018905,0.000000,0.000000,0.5,0.523810,0,...,0,0,0,0.5,0.600000,7.525424,0.000000,0.138859,0.000000,226.515254

In [27]:
df.shape

(691, 31)

In [28]:
y

0       0.268214
1       0.800359
5       0.800980
8       0.650417
9       0.750396
          ...
1183    0.750038
1185    0.850502
1187    0.600529
1191    0.700481
1195    0.611141
Name: efficiencyScore, Length: 691, dtype: float64

In [29]:
## Splitting the dataset into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((552, 27), (139, 27), (552,), (139,))

## Simple Linear Regression

In [30]:
from sklearn.linear_model import LinearRegression

L = LinearRegression()
L.fit(X_train, y_train)
y_pred_linear = L.predict(X_test)

In [31]:
from sklearn.metrics import mean_squared_error, r2_score

mse_linear = mean_squared_error(y_test, y_pred_linear)
r2_linear = r2_score(y_test, y_pred_linear)

print(f"Mean Squared Error (Simple Linear Regression): {mse_linear}")
print(f"R-squared (Simple Linear Regression): {r2_linear}")

Mean Squared Error (Simple Linear Regression): 0.00337787674142201
R-squared (Simple Linear Regression): 0.8092210520500588

# Decision Tree Regressor

In [32]:
from sklearn.tree import DecisionTreeRegressor

DT = DecisionTreeRegressor()
DT.fit(X_train, y_train)
y_pred_decision = DT.predict(X_test)

In [33]:
from sklearn.metrics import mean_squared_error, r2_score

mse_decision = mean_squared_error(y_test, y_pred_decision)
r2_decision = r2_score(y_test, y_pred_decision)

print(f"Mean Squared Error (Decision Tree Regressor): {mse_decision:.5f}")
print(f"R-squared (Decision Tree Regressor): {r2_decision:.5f}")

Mean Squared Error (Decision Tree Regressor): 0.00309
R-squared (Decision Tree Regressor): 0.82555

# Random Forest Regressor

In [34]:
from sklearn.ensemble import RandomForestRegressor

RF = RandomForestRegressor()
RF.fit(X_train, y_train)
y_pred_random = RF.predict(X_test)

In [35]:
from sklearn.metrics import mean_squared_error, r2_score

mse_random = mean_squared_error(y_test, y_pred_random)
r2_random = r2_score(y_test, y_pred_random)

print(f"Mean Squared Error (Random Forest Regressor): {mse_random:.5f}")
print(f"R-squared (Random Forest Regressor): {r2_random:.5f}")

Mean Squared Error (Random Forest Regressor): 0.00157
R-squared (Random Forest Regressor): 0.91140

# Gradient Boosting Regressor

In [36]:
from sklearn.ensemble import GradientBoostingRegressor

GB = GradientBoostingRegressor()
GB.fit(X_train, y_train)
y_pred_gradient_boosting = GB.predict(X_test)

In [38]:
from sklearn.metrics import mean_squared_error, r2_score

mse_gradient_boosting = mean_squared_error(y_test, y_pred_gradient_boosting)
r2_gradient_boosting = r2_score(y_test, y_pred_gradient_boosting)

print(f"Mean Squared Error (Gradient Boosting Regressor): {mse_gradient_boosting:.5f}")
print(f"R-squared (Gradient Boosting Regressor): {r2_gradient_boosting:.5f}")

Mean Squared Error (Gradient Boosting Regressor): 0.00125
R-squared (Gradient Boosting Regressor): 0.92942